version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker-compose/compute_wrapper
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/csharp/npgsql
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test_runner/pg_clients/csharp/npgsql
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/java/jdbc
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/python/asyncpg
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test_runner/pg_clients/python/asyncpg
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/python/pg8000
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test_runner/pg_clients/python/pg8000
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /test_runner/pg_clients/rust/tokio-postgres
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/rust/tokio-postgres
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/swift/PostgresClientKitExample
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/swift/PostgresNIOExample
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/typescript/postgresql-client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test_runner/pg_clients/typescript/postgresql-client
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test_runner/pg_clients/typescript/serverless-driver
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /test_runner/pg_clients/typescript/serverless-driver
    schedule:
      interval: daily
