name: Lint GitHub Workflows

on:
  push:
    branches:
      - main
      - release
    paths:
      - '.github/workflows/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check-permissions:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'run-no-ci') }}
    uses: ./.github/workflows/check-permissions.yml
    with:
      github-event-name: ${{ github.event_name}}

  actionlint:
    needs: [ check-permissions ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install actionlint shellcheck zizmor

      - uses: neondatabase/dev-actions/actions-linters@bayandin/add-actions-linters
